project_id = "yvdfdmyusdhgtzfguxbj"

[functions.sarelli]
verify_jwt = false

[functions.criar-usuario]
verify_jwt = false

[functions.listar-usuarios]
verify_jwt = false

[functions.gerenciar-usuario]
verify_jwt = false

[functions.limpar-localizacao]
verify_jwt = false